In [1]:
#RESHAPING

In [3]:
import numpy as np
from numpy.random import randint as ri

In [4]:
a =ri(1,99,30)
b=a.reshape(2,3,5)
c=a.reshape(6,5)

In [5]:
a

array([24, 28,  2, 92, 21, 46, 16, 94, 61, 40, 78, 18, 31, 71, 84,  2, 71,
       20,  8, 83, 37,  8, 89, 84,  5, 17, 62, 63, 48, 54])

In [6]:
b

array([[[24, 28,  2, 92, 21],
        [46, 16, 94, 61, 40],
        [78, 18, 31, 71, 84]],

       [[ 2, 71, 20,  8, 83],
        [37,  8, 89, 84,  5],
        [17, 62, 63, 48, 54]]])

In [7]:
c

array([[24, 28,  2, 92, 21],
       [46, 16, 94, 61, 40],
       [78, 18, 31, 71, 84],
       [ 2, 71, 20,  8, 83],
       [37,  8, 89, 84,  5],
       [17, 62, 63, 48, 54]])

In [8]:
print("Shape of a:",a.shape)
print("Shape of b:",b.shape)
print("Shape of c:",c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [10]:
print("\n a looks like \n",'-'*20,"\n",a,"\n",'-'*20)
print("\n b looks like \n",'-'*20,"\n",b,"\n",'-'*20)
print("\n c looks like \n",'-'*20,"\n",c,"\n",'-'*20)


 a looks like 
 -------------------- 
 [24 28  2 92 21 46 16 94 61 40 78 18 31 71 84  2 71 20  8 83 37  8 89 84
  5 17 62 63 48 54] 
 --------------------

 b looks like 
 -------------------- 
 [[[24 28  2 92 21]
  [46 16 94 61 40]
  [78 18 31 71 84]]

 [[ 2 71 20  8 83]
  [37  8 89 84  5]
  [17 62 63 48 54]]] 
 --------------------

 c looks like 
 -------------------- 
 [[24 28  2 92 21]
 [46 16 94 61 40]
 [78 18 31 71 84]
 [ 2 71 20  8 83]
 [37  8 89 84  5]
 [17 62 63 48 54]] 
 --------------------


In [12]:
A = ri(1,100,10)        #vector from random numbers
print("\n vector of of integers \n",'-'*50,"\n",A)
print("\n Here is the sorted vector \n",'-'*50,"\n",np.sort(A, kind='quicksort'))


 vector of of integers 
 -------------------------------------------------- 
 [81 42 22 16 71 48 28 89 99 56]

 Here is the sorted vector 
 -------------------------------------------------- 
 [16 22 28 42 48 56 71 81 89 99]


In [15]:
M = ri(1,100,25).reshape(5,5)
print("\n 5*5 matrix of random integers \n",'-'*50,"\n",M)
print("\n Here is the sorted matrix along each row \n",'-'*50,"\n",np.sort(M))
print("\n Here is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0,kind='mergesort'))


 5*5 matrix of random integers 
 -------------------------------------------------- 
 [[30 13 16 22  4]
 [45  3 49 63 12]
 [21 39 60 88 10]
 [98 51 10 25 94]
 [47  7 53 22  7]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[ 4 13 16 22 30]
 [ 3 12 45 49 63]
 [10 21 39 60 88]
 [10 25 51 94 98]
 [ 7  7 22 47 53]]

 Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[21  3 10 22  4]
 [30  7 16 22  7]
 [45 13 49 25 10]
 [47 39 53 63 12]
 [98 51 60 88 94]]


In [16]:
M

array([[30, 13, 16, 22,  4],
       [45,  3, 49, 63, 12],
       [21, 39, 60, 88, 10],
       [98, 51, 10, 25, 94],
       [47,  7, 53, 22,  7]])

In [17]:
print("\n Here is sorted matrix along each column\n ",'-'*50,"\n",np.sort(M,axis=0,kind='mergesort'))


 Here is sorted matrix along each column
  -------------------------------------------------- 
 [[21  3 10 22  4]
 [30  7 16 22  7]
 [45 13 49 25 10]
 [47 39 53 63 12]
 [98 51 60 88 94]]


In [18]:
a

array([24, 28,  2, 92, 21, 46, 16, 94, 61, 40, 78, 18, 31, 71, 84,  2, 71,
       20,  8, 83, 37,  8, 89, 84,  5, 17, 62, 63, 48, 54])

In [19]:
print("max of a:",a.max())

max of a: 94


In [20]:
print("min of b:",b.min())

min of b: 2
