In [2]:
#ARANGE AND LINSPACE

In [3]:
import numpy as np

In [4]:
list(range(2,10.5,.4))     #range is not in integer so output is erroe

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
a = np.arange(2,10.5,.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [6]:
# REVERSE ORDER

In [7]:
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [8]:
for i in np.arange(2,10.5,.4):
    if i==5.6:
        print(i)
    else:
            continue
                  

5.6


In [10]:
print("Every 5th number from 50 in reverse order \n",np.arange(50,0,-5))

Every 5th number from 50 in reverse order 
 [50 45 40 35 30 25 20 15 10  5]


In [11]:
print("linesrly spaced between the numbers 10 and 5 \n------------------------")
print(np.linspace(10,40,3))

linesrly spaced between the numbers 10 and 5 
------------------------
[10. 25. 40.]
