BROADCASTING

In [2]:
import numpy as np

In [3]:
start = np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#CREATE A RANK1 NDARRAY WITH 3 VALUES

In [5]:
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [6]:
y = start+add_rows          #add add rows to the start matrix
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [7]:
#CREATE AN ARRAY WHICH IS 4*1 TO BROADCAST ACROSS COLUMNS

In [9]:
add_cols = np.array([[0,1,2,3]])
print(add_cols)

[[0 1 2 3]]


In [10]:
add_cols = add_cols.T  # T is transverse function
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [11]:
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# this will just broadcast in both the dimentions 


In [14]:
add_scalar = np.array([100])
print(start+add_scalar)

[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]
