In [ ]:
#RANDOM NUMBER GENERATION

In [1]:
import numpy as np

In [2]:
print("Random number generation (from uniform distribution)")
print(np.random.rand(10,5))          #Rand = 0to1 all +ve numbers

Random number generation (from uniform distribution)
[[0.03619641 0.17959533 0.34616379 0.04231357 0.7407477 ]
 [0.09456013 0.26614991 0.07046563 0.67984436 0.32875169]
 [0.1484034  0.38294351 0.82970366 0.8664964  0.04778593]
 [0.67841804 0.45637887 0.96568883 0.81053173 0.61224078]
 [0.29109162 0.01085681 0.39716808 0.90063669 0.05057198]
 [0.69557555 0.01170133 0.05448504 0.01755804 0.89892512]
 [0.84568524 0.38744603 0.41898848 0.92271322 0.66301199]
 [0.88528222 0.11717832 0.2476242  0.1558493  0.3659505 ]
 [0.2141291  0.38126475 0.06323893 0.94765676 0.09992578]
 [0.03790119 0.40445174 0.99795808 0.92143641 0.67867457]]


In [3]:
print("Numberts from Normal distribution with zero mean and std deviation 1 thatr is standard normal ")
print(np.random.randn(10,2))    #GENERATION OF ALL +VE AND -VE NUMBERS

Numberts from Normal distribution with zero mean and std deviation 1 thatr is standard normal 
[[-1.89326127 -0.72791172]
 [-0.33262774  0.21149785]
 [-0.862614   -0.40363644]
 [ 1.06426304  0.59613785]
 [-1.4237002  -0.50335289]
 [ 1.55699886 -0.23091156]
 [-0.05287857  0.78066288]
 [ 0.65471492 -0.7300959 ]
 [ 0.66294273 -0.62308442]
 [ 0.29283339  0.08424136]]


In [9]:
print("\n Random integer vector:",np.random.randint(1,6,10))    #GENERATION OF INTEGER


 Random integer vector: [1 3 1 5 4 2 1 1 4 4]


In [11]:
print("\n Random integer matrix")
print(np.random.randint(1,30,(4,4)))


 Random integer matrix
[[ 1 26 25 15]
 [23  6 24  6]
 [ 3 27 25 27]
 [29 27  2 13]]


In [12]:
print("\n 20 samples drawn from dice thrown:",np.random.randint(1,7,20))


 20 samples drawn from dice thrown: [4 4 4 4 5 1 6 2 1 2 5 3 1 6 1 6 2 2 3 6]
