In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
arr = np.array(my_list)
print("Type / class of the object",type(arr))
print("Here is the vector \n -------------------------\n",arr)

Type / class of the object <class 'numpy.ndarray'>
Here is the vector 
 -------------------------
 [1 2 3]


In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/class of the object",type(mat))
print("Here the matrix is \n---------------------------\n",mat,"\n-------")
print("Dimenstion of the matrix :",mat.ndim,sep='')  #gives(ndim) the dimensation 2 for matrix 1 for vector
print("Size of the matrix :",mat.size,sep='')        #mat.size gives total number of elements 
print("Shape of the matrix:",mat.shape)                #shape gives rows and columns
print("Data type of this matrix :",mat.dtype)        #dtypes gives the data types contained in the array

Type/class of the object <class 'numpy.ndarray'>
Here the matrix is 
---------------------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-------
Dimenstion of the matrix :2
Size of the matrix :9
Shape of the matrix: (3, 3)
Data type of this matrix : int32
