##UNIVERSAL FUNCTION 

In [4]:
import numpy as np
from numpy.random import randint as ri

In [5]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n 1st matrix of random single digit numbers \n",mat1)
print("\n 2nd matrix of random single digit numbers \n",mat2)


 1st matrix of random single digit numbers 
 [[2 7 6]
 [5 7 6]
 [4 3 1]]

 2nd matrix of random single digit numbers 
 [[3 2 8]
 [6 7 1]
 [6 1 4]]


In [6]:
print("\n Addition \n-------------------------------\n",mat1+mat2)
print("\n Multiplication \n-------------------------------\n",mat1*mat2)


 Addition 
-------------------------------
 [[ 5  9 14]
 [11 14  7]
 [10  4  5]]

 Multiplication 
-------------------------------
 [[ 6 14 48]
 [30 49  6]
 [24  3  4]]


In [7]:
print("\n Division \n-----------------------------\n",mat1/mat2)
print("\n Linear combination:3*A-2*B \n----------------------n",3*mat1-2*mat2)


 Division 
-----------------------------
 [[0.66666667 3.5        0.75      ]
 [0.83333333 1.         6.        ]
 [0.66666667 3.         0.25      ]]

 Linear combination:3*A-2*B 
----------------------n [[ 0 17  2]
 [ 3  7 16]
 [ 0  7 -5]]


In [8]:
print("\n Addition of scalar (100)\n------------------\n",100+mat1)
new_mat = 100+mat1


 Addition of scalar (100)
------------------
 [[102 107 106]
 [105 107 106]
 [104 103 101]]


In [9]:
new_mat

array([[102, 107, 106],
       [105, 107, 106],
       [104, 103, 101]])

In [10]:
print("\n exponential matrix cubed have here \n-----------------------------------\n",mat1**3)


 exponential matrix cubed have here 
-----------------------------------
 [[  8 343 216]
 [125 343 216]
 [ 64  27   1]]


In [11]:
print("\n sq.root using polar function \n------------------------------------\n",pow(mat1,.5))


 sq.root using polar function 
------------------------------------
 [[1.41421356 2.64575131 2.44948974]
 [2.23606798 2.64575131 2.44948974]
 [2.         1.73205081 1.        ]]


In [12]:
mat1

array([[2, 7, 6],
       [5, 7, 6],
       [4, 3, 1]])

In [13]:
mat2

array([[3, 2, 8],
       [6, 7, 1],
       [6, 1, 4]])

In [14]:
print("\n sq.root of 1st matrix using np \n---------------------------------\n",np.sqrt(mat1))


 sq.root of 1st matrix using np 
---------------------------------
 [[1.41421356 2.64575131 2.44948974]
 [2.23606798 2.64575131 2.44948974]
 [2.         1.73205081 1.        ]]


In [15]:
print("\n exponential power of 1st matrix using np \n---------------------------------\n",np.exp(mat1))


 exponential power of 1st matrix using np 
---------------------------------
 [[   7.3890561  1096.63315843  403.42879349]
 [ 148.4131591  1096.63315843  403.42879349]
 [  54.59815003   20.08553692    2.71828183]]


In [16]:
print("\n 10 base logaritham np \n---------------------------------\n",np.log10(mat1))


 10 base logaritham np 
---------------------------------
 [[0.30103    0.84509804 0.77815125]
 [0.69897    0.84509804 0.77815125]
 [0.60205999 0.47712125 0.        ]]


In [17]:
np.log(3)

1.0986122886681098