In [2]:
import numpy as np

In [3]:
print("Vector of zero's \n-------------------------")
print(np.zeros(5))

Vector of zero's 
-------------------------
[0. 0. 0. 0. 0.]


In [4]:
print("Matrix of zero's\n----------------------------")
print(np.zeros((10,14)))

Matrix of zero's
----------------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
print("vector of one\n---------------------------")
print(np.ones((5,2)))

vector of one
---------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
print("matrix of 5's \n-----------------------------------")
print(5*np.ones((10,5)))

matrix of 5's 
-----------------------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [10]:
mat1 = np.eye(5)
print("Identity matrix of dimention ",mat1.shape)
print(mat1)

Identity matrix of dimention  (5, 5)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
np.linspace(2.0,3.0,num=4,endpoint=False)

array([2.  , 2.25, 2.5 , 2.75])

In [12]:
#retstep is the step size separating from samples

In [13]:
np.linspace(2.2345,10.35689,num=25,retstep=True)

(array([ 2.2345    ,  2.57293292,  2.91136583,  3.24979875,  3.58823167,
         3.92666458,  4.2650975 ,  4.60353042,  4.94196333,  5.28039625,
         5.61882917,  5.95726208,  6.295695  ,  6.63412792,  6.97256083,
         7.31099375,  7.64942667,  7.98785958,  8.3262925 ,  8.66472542,
         9.00315833,  9.34159125,  9.68002417, 10.01845708, 10.35689   ]),
 0.33843291666666664)

In [14]:
np.logspace(2.0,3.0,num=4,endpoint=True)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [15]:
#constract diagonal matrix

In [16]:
x = np.arange(36).reshape(6,6)

In [17]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
np.diag(x)

array([ 0,  7, 14, 21, 28, 35])

In [19]:
#SHIFT AND 4 TIMES TAB FOR ALL FUNCTIONS