In [1]:
import numpy as np

In [2]:
np.array([5,9,13])

array([ 5,  9, 13])

In [3]:
type([5,9,13])

list

In [4]:
np.array([1,2,13])

array([ 1,  2, 13])

In [5]:
#TWO DIMENSTATION

In [8]:
a = np.array([[1,2],[3,4],[4,5]])
a.dtype

dtype('int32')

In [9]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [10]:
#MINIMUM DIMENSTAION 2:
#D TYPE

In [11]:
np.array([1,2,3],dtype=float)    #CONVERT INTO TO FLOAT

array([1., 2., 3.])

In [12]:
# CREATING ARRAY USING .MAT(MATRIX)

In [14]:
np.array(np.mat('1 2 3;3 4 5'))

array([[1, 2, 3],
       [3, 4, 5]])

In [15]:
#CONVERT A LIST INTO AN ARRAY

In [16]:
a = [1,2]
np.array(a)

array([1, 2])

In [17]:
#COPYING DATA

In [18]:
b = np.asarray(a)

In [19]:
b

array([1, 2])