In [18]:
#INDEXING AND SLICING

In [19]:
import numpy as np
from numpy.random import randint as ri

In [20]:
arr = np.arange(0,11)
print("Array",arr)

Array [ 0  1  2  3  4  5  6  7  8  9 10]


In [21]:
print("Element at 7th index is:",arr[7])

Element at 7th index is: 7


In [22]:
print("Elements from 3rd to 5th index are:",arr[3:6])

Elements from 3rd to 5th index are: [3 4 5]


In [23]:
print("Elements upto 4th index are:",arr[4:])

Elements upto 4th index are: [ 4  5  6  7  8  9 10]


In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
print("Elements from last backwords are:",arr[-1::-2])         #[-1::-2] -2 is stepsize from end point

Elements from last backwords are: [10  8  6  4  2  0]


In [26]:
print("7 Elements from last backwords are:",arr[-1:-8:-1])        #[-1:-8:-1]  -1 is ending point -8 is strting point -1 is stepsize

7 Elements from last backwords are: [10  9  8  7  6  5  4]


In [27]:
arr = np.arange(0,21,2)
print("New Array",arr)

New Array [ 0  2  4  6  8 10 12 14 16 18 20]


In [28]:
print("Elements at 2nd,4th and 9th index are:",arr[[2,4,9]])          #pass list as integer as index to subset

Elements at 2nd,4th and 9th index are: [ 4  8 18]


In [31]:
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [33]:
a = ri(1,99,9).reshape(3,3)

In [34]:
a

array([[58, 31, 76],
       [45, 43, 90],
       [53, 93, 74]])

In [36]:
print("\n Double bracket indexing \n------------------------------------")
print("Elements in row index 1 and column index2:",a[2][1])


 Double bracket indexing 
------------------------------------
Elements in row index 1 and column index2: 93


In [37]:
a

array([[58, 31, 76],
       [45, 43, 90],
       [53, 93, 74]])

In [38]:
print("Entire row at index 2:",a[2])
print("Entire column at index 2:",a[:,1:])

Entire row at index 2: [53 93 74]
Entire column at index 2: [[31 76]
 [43 90]
 [93 74]]


In [39]:
print("\n Subsetting sub_matrices \n______________________________________")
print("Matrix with row induces 1 and 2 and column indices 3 and 4 \n",a[1:2,1:2])


 Subsetting sub_matrices 
______________________________________
Matrix with row induces 1 and 2 and column indices 3 and 4 
 [[43]]


In [40]:
a

array([[58, 31, 76],
       [45, 43, 90],
       [53, 93, 74]])

In [41]:
print("",a[0:2,[1,2]])

 [[31 76]
 [43 90]]


In [42]:
# SUBSETTING

In [43]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2 digit numbers \n---------------------------------\n",mat)

Matrix of random 2 digit numbers 
---------------------------------
 [[10 89 49 31 66]
 [86 98 19 95 24]
 [30 47 28 61 72]]


In [46]:
print("Elements greater than 50 \n",mat[mat>50])

Elements greater than 50 
 [89 66 86 98 95 61 72]


In [47]:
mat>50

array([[False,  True, False, False,  True],
       [ True,  True, False,  True, False],
       [False, False, False,  True,  True]])

#SLICING

In [50]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("original matrix")
print(mat)

original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [51]:
mat_slice = mat[:2,:2]
print("\n Sliced matrix \n")
print(mat_slice)
print("\n Change the sliced matrix")


 Sliced matrix 

[[11 12]
 [21 22]]

 Change the sliced matrix


In [52]:
mat_slice[0,0] =1000
print(mat_slice)                #Updatring with new number

[[1000   12]
 [  21   22]]


In [53]:
print("\n but the original matrix ? whoa! it got changed too!")
print(mat)


 but the original matrix ? whoa! it got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [54]:
# little differant way to create a copy of the sliced matrix

In [55]:
print("\n Doing again it little differantly now ------------------------\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


 Doing again it little differantly now ------------------------

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]
